# Generated by Django 4.0.5 on 2022-06-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_remove_dish_category_dish_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='categories',
        ),
    ]
