# Generated by Django 4.0.5 on 2022-07-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_rename_category_dish_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
