# Generated by Django 4.0.5 on 2022-07-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_basicuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicUser',
        ),
    ]
