# Generated by Django 4.0.5 on 2022-07-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0007_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='categories',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.category', verbose_name='Категория'),
        ),
    ]
