# Generated by Django 4.0.5 on 2022-07-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0008_remove_dish_categories_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.category', verbose_name='Категория'),
        ),
    ]
