# Generated by Django 4.0.5 on 2022-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0010_remove_category_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cooking_time_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Время приготовления'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cooking_time_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Время приготовления'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_en',
            field=models.TextField(null=True, verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_ru',
            field=models.TextField(null=True, verbose_name='Рецепт'),
        ),
    ]
