# Generated by Django 4.0.5 on 2022-07-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0011_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menuapp.dish', verbose_name='блюдо'),
        ),
    ]
