# Generated by Django 4.0.6 on 2022-07-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0013_alter_reviews_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.dish', verbose_name='блюдо'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.reviews', verbose_name='Родитель'),
        ),
    ]
